resources:
  projectroot:
spring:
  view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp
  groovy:
    template:
      cache: false
      prefix: classpath:/groovy/


app:
  version: de4db33f
config:
  AUTH_URL: pl_AUTH_URL_localhost
  NOTIFY_HOST: pl_NOTIFY_HOST_localhost
  UPLOAD_HOST: pl_UPLOAD_HOST_localhost
  NGROKMODE: pl_NGROKMODE_mode_ok
  AJAX_PROTOCOL: false
  AJAX_URL_START: 0
  TRANSLOADIT_KEY: tl_key
  TRANSLOADIT_FILE_TEMPLATE_ID:  tl_file_id
  TRANSLOADIT_IMAGE_TEMPLATE_ID: tl_image_id
  TRANSLOADIT_VIDEO_TEMPLATE_ID: tl_video_id
  MIXPANEL_TOKEN: mx12345
  SENDER_ID: send12345
  BUGSENSE_API_KEY_STUDENT: sense12345
  APP_VERSION: 1.0.0
